<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tester-VirtualBox" name="Default test" tests="4" failures="0" timestamp="19 Feb 2020 20:09:33 GMT" time="0.037" errors="0">
  <testcase name="@BeforeClass setUp" time="0.0" classname="unittesting.parcijalni.StudentServiceTest">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	The declared package &amp;quot;unittesting.student&amp;quot; does not match the expected package &amp;quot;unittesting.parcijalni&amp;quot;
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The declared package "unittesting.student" does not match the expected package "unittesting.parcijalni"

	at unittesting.parcijalni.StudentService.<init>(StudentService.java:1)
	at unittesting.parcijalni.StudentServiceTest.setUp(StudentServiceTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass setUp -->
  <testcase name="testStudentNoMany" time="0.001" classname="unittesting.parcijalni.StudentServiceTest">
    <skipped/>
  </testcase> <!-- testStudentNoMany -->
  <testcase name="testStudentNotActiv" time="0.001" classname="unittesting.parcijalni.StudentServiceTest">
    <skipped/>
  </testcase> <!-- testStudentNotActiv -->
  <testcase name="testStudnet" time="0.001" classname="unittesting.parcijalni.StudentServiceTest">
    <skipped/>
  </testcase> <!-- testStudnet -->
  <testcase name="testWithException" time="0.0" classname="unittesting.parcijalni.StudentServiceTest">
    <skipped/>
  </testcase> <!-- testWithException -->
</testsuite> <!-- Default test -->
